consul:
  image: autopilotpattern/consul:0.7.3r39
  restart: always
  dns:
    - 127.0.0.1
  labels:
    - triton.cns.services=consul
  ports:
    - "8500:8500"
  command: >
    /usr/local/bin/containerpilot
  environment:
    - CONSUL_DEV=1
prometheus:
    image: autopilotpattern/prometheus:1.7.1-r20
    restart: always
    ports:
      - "9090:9090"
    links:
      - consul:consul
    environment:
      - CONSUL=consul
      - CONSUL_AGENT=1
    dns:
      - 127.0.0.1
nats:
    image: autopilotpattern/nats:0.9.6-r1.0.0
    restart: always
    ports:
      - 8222
    links:
      - consul:consul
    environment:
      - CONSUL=consul
      - CONSUL_AGENT=1
      - NATS_USER=ruser
      - NATS_PASSWORD=password
natsboard:
    image: d0cker/natsboard
    restart: always
    ports:
      - "3000:3000"
      - "3001:3001"
    links:
      - consul:consul
    environment:
      - CONSUL=consul
      - CONSUL_AGENT=1
traefik:
    build: ./traefik
    ports:
      - "80:80"
      - "8080:8080"
    links:
      - consul:consul
    environment:
      - CONSUL=consul
    restart: always
influxdb:
  image: autopilotpattern/influxdb:1.1.1
  ports:
    - "8086:8086"
    - "8083:8083"
  restart: always
  links:
    - consul:consul
  environment:
    - CONSUL=consul
    - ADMIN_USER=root
    - INFLUXDB_INIT_PWD=root123
    - INFLUXDB_ADMIN_ENABLED=true
    - INFLUXDB_REPORTING_DISABLED=true
    - INFLUXDB_DATA_QUERY_LOG_ENABLED=false
    - INFLUXDB_HTTP_LOG_ENABLED=false
    - INFLUXDB_CONTINUOUS_QUERIES_LOG_ENABLED=false
serializer:
  build: ./serializer
  links:
    - consul:consul
  environment:
    - PORT=10000
    - CONSUL=consul
    - INFLUXDB_USER=root
    - INFLUXDB_PWD=root123
  expose:
    - 10000
    - 9090
  restart: always
frontend:
  build: ./frontend
  links:
    - consul:consul
  environment:
    - CONSUL=consul
    - PORT=10001
  expose:
    - 10001
    - 9090
  restart: always
smartthings:
  build: ./smartthings
  links:
    - consul:consul
  expose:
    - 8080
  environment:
    - PORT=8080
    - CONSUL=consul
    - NATS_USER=ruser
    - NATS_PASSWORD=password
    - FAKE_MODE=true
  restart: always
humidity:
  build: ./sensor
  links:
    - consul:consul
  environment:
    - SENSOR_TYPE=humidity
    - CONSUL=consul
    - NATS_USER=ruser
    - NATS_PASSWORD=password
  restart: always
motion:
  build: ./sensor
  links:
    - consul:consul
  environment:
    - SENSOR_TYPE=motion
    - CONSUL=consul
    - NATS_USER=ruser
    - NATS_PASSWORD=password
  restart: always
temperature:
  build: ./sensor
  links:
    - consul:consul
  environment:
    - SENSOR_TYPE=temperature
    - CONSUL=consul
    - NATS_USER=ruser
    - NATS_PASSWORD=password
  restart: always
